name: Tests


on: [push, pull_request]

jobs:

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        args: [
            "--no-default-features",
            # // test seperately from --all-features since for secp256kfun this will enable parity backend
            "--no-default-features --features=std,serde,libsecp_compat",
            "--no-default-features --features=std,serde,libsecp_compat,nightly",
            "--all-features",
            ""
        ]
        rust: [nightly, stable]
        target: ["x86_64-unknown-linux-gnu", "armv7-unknown-linux-gnueabihf"]
        exclude:
          - rust: stable
            args: --all-features
          - rust: stable
            args: "--no-default-features --features=std,serde,libsecp_compat,nightly"
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - name: Install compiler for armhf arch
        if: matrix.target == 'armv7-unknown-linux-gnueabihf'
        run: |
          sudo apt-get update
          sudo apt-get install gcc-arm-linux-gnueabihf
      - uses: Swatinem/rust-cache@v1.2.0
      - run: cargo test ${{ matrix.args }} --release --verbose --target ${{ matrix.target }}

  doc-build:
     name: doc-build
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: actions-rs/toolchain@v1
         with:
           profile: minimal
           toolchain: nightly
           override: true
       - name: build-doc
         # convoluted way to make it fail on warnings
         run: "cargo doc --no-deps --workspace --exclude secp256kfun_parity_backend 2>&1 | tee /dev/fd/2 | grep -iEq '^(warning|error)' && exit 1 || exit 0"
